### ISSUE TITLE
Errors in running Phantomjs

### ISSUE THREAD

**Issue by mangeshkhaire14** [codeforequity-at/botium-connector-webdriverio#1]
Hi, 

I am getting following errors when running phantom js. This is probably due to the selenium server is running port 4444. Can you please tell how we can run the phantom js on different port. I tried with port 5555 but it did not work. also can you please tell me exact command to run with the port option.

[ERROR - 2018-12-28T09:40:28.243Z] GhostDriver - main.fail - {"line":85,"sourceURL":"phantomjs://code/main.js","stack":"global code@phantomjs://code/main.js:85:56"}

  phantomjs://platform/console++.js:263 in error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botium-connector-webdriverio@0.0.10 phantomjs: `phantomjs --webdriver=4444`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the botium-connector-webdriverio@0.0.10 phantomjs script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GS-1982\AppData\Roaming\npm-cache\_logs\2018-12-28T09_40_28_314Z-debug.log

**Comment by codeforequity-at** [comment]
You should run phantomjs with the "--webdriver=port" option. If it doesn't work for you this is a question  you should ask in a phantomjs forum, the experts are over there ...
