### ISSUE TITLE
npm install failing in samples->botbuilderwebchat

### ISSUE THREAD

**Issue by hitesh22nov** [codeforequity-at/botium-connector-webdriverio#3]
Following error is displayed in npm install for botbuilderwebchat

erwebchat> npm install
npm WARN samples@1.0.0 No description
npm WARN samples@1.0.0 No repository field.

npm ERR! path C:\Users\hiteshyadav\Desktop\ChatAuto\UnderTest\botium-connector-webdriverio-master\botium-connector-webdriverio-master\samples\botbuilderwebchat\node_modules\.staging\botium-connector-webdriverio-a26a90de\node_modules\@types\estree
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename

**Comment by codeforequity-at** [comment]
https://github.com/codeforequity-at/botium-core/wiki/Troubleshooting#problems-with-npm-install
